# Starter pipeline


trigger:
- main
- develop
- feature/*

pool:
  name: linux

variables:
- group: azure_deployment

steps:
- task: AzureStaticWebApp@0
  inputs:
    verbose: true
    azure_static_web_apps_api_token: $(azure_deployment_token)
    skip_app_build: true
    skip_api_build: true
    app_location: 'src'
    api_location: 'api'