# Starter pipeline


trigger:
- main

pool:
  name: linux

variables:
- group: azure_deployment

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureStaticWebApp@0
  inputs:
    verbose: true
    azure_static_web_apps_api_token: $(azure_deployment_token)
    skip_app_build: true
    skip_api_build: true