steps:
- checkout: none

- task: DownloadBuildArtifacts@0
  displayName: 'Download Azure functions artifact'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'BackendFunctions'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: DownloadBuildArtifacts@0
  displayName: 'Download SWA artifact'
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'SWA'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: ExtractFiles@1
  displayName: 'Unzip SWA artifact'
  inputs:
    archiveFilePatterns: '$(System.ArtifactsDirectory)/SWA/swa*.zip'
    destinationFolder: '$(System.ArtifactsDirectory)/staticwebapp' 

- task: AzureFunctionApp@1
  displayName: 'Deploy Azure functions'
  inputs:
    azureSubscription: 'Azure Visual Studio Subscription'
    appType: 'functionAppLinux'
    appName: '$(functions_app_name)'
    package: '$(System.ArtifactsDirectory)/BackendFunctions/functions_$(Build.BuildId).zip'
    runtimeStack: 'NODE|$(nodeVersion)'

- task: AzureStaticWebApp@0
  displayName: 'Deploy Azure Static Web App'
  inputs:
    verbose: true
    azure_static_web_apps_api_token: $(azure_deployment_token)
    skip_app_build: true
    skip_api_build: true
    app_location: '$(System.ArtifactsDirectory)/staticwebapp/public'
    api_location: '$(System.ArtifactsDirectory)/staticwebapp/api'