trigger:
- main
- develop
- feature/*

pool:
  name: linux

variables:
- name: nodeVersion
  value: 18

stages:
- stage: Dev
  variables:
  - group: azure_deployment_dev
  jobs:
  - job: DeployDev
    steps:
    - template: azure-pipelines-deploy.yml

- stage: Prod
  #condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  variables:
  - group: azure_deployment_prod
  jobs:
  - job: DeployProd
    steps:
    - template: azure-pipelines-deploy.yml