# Starter pipeline


trigger:
- main
- develop
- feature/*

pool:
  name: linux

variables:
- group: azure_deployment

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'functions'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/functions'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/functions_$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure Visual Studio Subscription'
    appType: 'functionAppLinux'
    appName: 'vvdotcr-backend-functions-dev'
    package: '$(Build.ArtifactStagingDirectory)/functions_$(Build.BuildId).zip'
    runtimeStack: 'NODE|16'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'api'

- task: AzureStaticWebApp@0
  inputs:
    verbose: true
    azure_static_web_apps_api_token: $(azure_deployment_token)
    skip_app_build: true
    skip_api_build: true
    app_location: 'src'
    api_location: 'api'